language: cpp
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - g++-7
compiler:
- g++-7
os:
- linux
branches:
  only:
  - master
notifications:
  email: false
install:
  - "[ $CXX = g++ ] && export CXX=g++-7.3.0 || true"
  - cd scr
script:
  - make
  - make test
